# {% include 'template/license_header' %}

# environment configuration
settings:
  docker:
    required_integrations:
      - aws
{%- if data_quality_checks %}
      - evidently
{%- endif %}
      - kubeflow
      - kubernetes
      - mlflow
      - sklearn
      - slack

# configuration of steps  
steps:
  model_trainer:
    parameters:
      name: {{ product_name }}
{%- if metric_compare_promotion %}
  promote_with_metric_compare:
{%- else %}
  promote_latest_version:
{%- endif %}
    parameters:
      mlflow_model_name: {{ product_name }}
  notify_on_success:
    parameters:
      notify_on_success: False

# configuration of the Model Control Plane
model:
  name: {{ product_name }}
  license: {{ open_source_license }}
  description: |
    Advanced forecasting model designed to optimize supply chain operations for manufacturing.
    The model predicts demand, lead times, and inventory requirements for critical components
    and raw materials, helping maintain optimal production schedules while minimizing inventory costs.

  audience: |
{%- for audience in audience %}
    - {{ audience }}
{%- endfor %}
  use_cases: |
{%- for use_case in use_cases %}
    - {{ use_case }}
{%- endfor %}
  limitations: |
    - Requires minimum 3 years of historical data for optimal performance
    - May need recalibration during major market disruptions
    - Limited accuracy for newly introduced components
  ethics: |
{%- if project_risk == 'unacceptable' %}
    Unacceptable Risk:
    - Manipulates behavior subliminally, exploiting vulnerable individuals.
    - Enables real-time biometric surveillance in public spaces without legal justification.
    - Facilitates social scoring systems leading to unjust or discriminatory treatment.
{%- elif project_risk == 'high' %}
    High Risk:
    - Processes sensitive personal data affecting health, safety, or fundamental rights.
    - Used in critical sectors like law enforcement, employment, or essential services.
    - Requires stringent risk mitigation, human oversight, and data transparency.
{%- elif project_risk == 'limited' %}
    Limited Risk:
    - Processes personal data with moderate implications for user rights.
    - Includes systems like chatbots or AI-generated content requiring clear labeling.
    - Transparency obligations ensure users are informed of AI involvement.
{%- else %}
    Minimal or No Risk:
    - Operates with negligible impact on user safety or privacy.
    - Applications include AI-enhanced video games or spam filtering tools.
    - Requires no regulatory compliance under the AI Act framework.
{%- endif %}
  tags:
  - supply chain
  - {{ data_privacy_level }}
  - {{ project_risk }} risk

# pipeline level extra configurations
extra:
  notify_on_failure: True
# pipeline level parameters
parameters:
  target_env: {{ target_environment }}
{%- if hyperparameters_tuning %}
  # This set contains all the model configurations that you want 
  # to evaluate during hyperparameter tuning stage.
  model_search_space:
    random_forest:
      model_package: sklearn.ensemble
      model_class: RandomForestClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10
        n_estimators:
          range:
            start: 50
            end: 500
            step: 25
    decision_tree:
      model_package: sklearn.tree
      model_class: DecisionTreeClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10
{%- else %}
  # This model configuration will be used for the training stage.
  model_configuration:
    model_package: sklearn.tree
    model_class: DecisionTreeClassifier
    params:
      criterion: gini
      max_depth: 5
      min_samples_leaf: 3
{%- endif %}